# Generated by Django 4.1 on 2022-11-01 14:27

import django.core.validators
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                null=True,
                upload_to="static/videos_uploaded/%Y/%m",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
                verbose_name="video",
            ),
        ),
    ]
